import type { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import Footer from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/toaster"
import localFont from 'next/font/local'

const bankGothic = localFont({
  src: [
    // Light weights
    {
      path: '../../public/fonts/BankGothic-BTLight.ttf',  // Changed path
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/BankGothic-LightRegular.otf',  // Changed path
      weight: '300',
      style: 'normal',
    },
    
    // Regular weights
    {
      path: '../../public/fonts/BankGothic-Regular.ttf',  // Changed path
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/ufonts.com_bank-gothic-medium.ttf',  // Changed path
      weight: '500',  // Changed from 400 to 500 since it's a medium weight
      style: 'normal',
    },
    
    // Medium weight
    {
      path: '../../public/fonts/BankGothic-mediumbt.ttf',  // Changed path
      weight: '600',  // Medium is typically 500-600
      style: 'normal',
    },
    
    // Bold weight
    {
      path: '../../public/fonts/BankGothic-Bold.ttf',  // Changed path
      weight: '700',
      style: 'normal',
    }
  ],
  display: 'swap',
  variable: '--font-bankgothic'
})

export const metadata: Metadata = {
  title: "Nine Nerds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={bankGothic.variable}>
      <body className={bankGothic.className}>
        <Navbar />
        {children}
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}